spring.application.name=employeaap
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/gfgmicroservicesdemo?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Ganesh@89
spring.jpa.properties.hibernate.dialect =  org.hibernate.dialect.MySQL8Dialect

